name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cicd-security-app .

      - name: Run container
        run: docker run -d -p 3000:3000 cicd-security-app

      - name: Check app
        run: curl http://localhost:3000
